MODULES_TO_UNINSTALL = (
    ('alfa_amb_copy_po_line', 'no_backup'),
    ('account_journal_dashboard', 'no_backup'),
    ('import_journal_entry', 'no_backup'),
    ('bi_all_in_one_schedule_activity_v10', 'no_backup'),
    ('bi_import_bank_statement_line', 'no_backup'),
    ('list_editor', 'no_backup'),
    ('account_standard_report', 'no_backup'),
    ('sale_order_invoice_details', 'no_backup'),
    ('account_statement_import_file', 'no_backup'),
    ('theme_bootswatch', 'no_backup'),
    ('google_drive', 'no_backup'),
    ('sale_quotation_builder', 'no_backup'),
    ('backend_theme_v10', 'no_backup'),
    ('remittance_advice_report', 'no_backup'),
    ('web_widget_colorpicker', 'no_backup'),
    ('web_widget_time_delta', 'no_backup'),
    ('web_gantt_native', 'no_backup'),
    ('project_native', 'backup'),
    ('vit_currency_inverse_rate', 'no_backup'),
)
